name: Release Please

defaults:
  run:
    shell: bash

permissions: {}

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write # for create a release
      pull-requests: write # for open a pull request
      issues: write # for create labels
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ github.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
